### ISSUE TITLE
Cannot use host from `~/.ssh/config`

### ISSUE THREAD

**Issue by innocenzi** [TablePlus/Bolt-SQL-issue-tracker#1]
With TablePlus, when connecting via SSH, I could use the host name setup in `~/.ssh/config`. This doesn't work with Bolt, I have to use the actual IP address.

![CleanShot 2023-10-11 at 16 18 09](https://github.com/TablePlus/Bolt-SQL-issue-tracker/assets/16060559/d8e4994a-b72c-48db-8a4c-a7fbd7e1dfb3)

**Comment by huyphams** [comment]
Hi, we will add it in the next update.

**Comment by huyphams** [comment]
It's added in the build 42! just enter the hostname and it will work.
