### ISSUE TITLE
Refresh tables list

### ISSUE THREAD

**Issue by devope** [TablePlus/Bolt-SQL-issue-tracker#12]
How to? Couldn't find

**Comment by huyphams** [comment]
You just right click on the item and then refresh.

**Comment by huyphams** [comment]
<img width="304" alt="Screenshot 2024-01-20 at 12 55 59 PM" src="https://github.com/TablePlus/Bolt-SQL-issue-tracker/assets/3654622/58b7ee7e-f6b4-47b4-8186-4a9a32d02213">

**Comment by devope** [comment]
Thanks!
What if I don't have any table?

**Comment by huyphams** [comment]
It was added in the newest release where you can right click anywhere and select refresh.
