### ISSUE TITLE
All columns doesn't fit well enough

### ISSUE THREAD

**Issue by devope** [TablePlus/Bolt-SQL-issue-tracker#13]
<img width="301" alt="Screenshot 2024-01-21 at 00 17 01" src="https://github.com/TablePlus/Bolt-SQL-issue-tracker/assets/8249408/bb2235b0-d0e8-46b3-bc73-c080150875b7">

There is one columns that doesn't fit: `updated_at`

**Comment by sonswift** [comment]
Hi @devope, thanks for your feedback. This issue was fixed and will be included in the next update.
