### ISSUE TITLE
Please add duration stats for queries

### ISSUE THREAD

**Issue by jsanbae** [TablePlus/Bolt-SQL-issue-tracker#6]
Can you add query duration statistics next to total rows? 

Would be nice to have for query analysis.

Thanks!

**Comment by sonswift** [comment]
Hi @jsanbae, the next update will contain this improve. Thanks for your feedback.

**Comment by jsanbae** [comment]
> Hi @jsanbae, the next update will contain this improve. Thanks for your feedback.

I just saw the implementation, thanks a lot
