### ISSUE TITLE
Cannot update values directly from Data table.

### ISSUE THREAD

**Issue by olvrcrls** [TablePlus/Bolt-SQL-issue-tracker#8]
Query anything that will result some data, update that data.
The application will prompt a couple of buttons:

![image](https://github.com/TablePlus/Bolt-SQL-issue-tracker/assets/22299203/039e9177-f664-41ec-81e3-0ede6355a00f)

Once the `Commit` button is clicked after the data update, it doesn't really update the data column when you re-select the data again with a select query.

**Comment by sonswift** [comment]
Hi @olvrcrls, thank for you feedback. Could you give me a piece of your query? I could not reproduce this issue.

**Comment by huyphams** [comment]
Hi @olvrcrls which database are you using?

**Comment by olvrcrls** [comment]
> Hi @olvrcrls, thank for you feedback. Could you give me a piece of your query? I could not reproduce this issue.

Basically any result from a **SELECT** query. Update the data from there and commit, try to run the same select query with the same dataset that you updated, the changes does not push through.

**Comment by olvrcrls** [comment]
> Hi @olvrcrls which database are you using?

MySQL.

**Comment by olvrcrls** [comment]
I will send a recording in my free time. I am using MacOS Sonoma for this software

**Comment by sonswift** [comment]
Hi @olvrcrls, have you tried to run the updated query in the Preview dialog? 

![image](https://github.com/TablePlus/Bolt-SQL-issue-tracker/assets/4739616/69ffd20e-f8a3-41e4-a86c-023fb080d8b3)

**Comment by olvrcrls** [comment]
> Hi @olvrcrls, have you tried to run the updated query in the Preview dialog?
> 
> ![image](https://private-user-images.githubusercontent.com/4739616/285560018-69ffd20e-f8a3-41e4-a86c-023fb080d8b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA4Nzg1OTQsIm5iZiI6MTcwMDg3ODI5NCwicGF0aCI6Ii80NzM5NjE2LzI4NTU2MDAxOC02OWZmZDIwZS1mOGEzLTQxZTQtYTg2Yy0wMjNmYjA4MGQ4YjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjVUMDIxMTM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjE2MzI4ODc5OWNhZDE2YjE4MDQxMDBmOWY4MzhjZGQ5MGFjZTBiY2Y1M2VmZWI4YmE3N2IxODlhMjY2YjljOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.d7n5W93_rR2w7zW7mYV_PRohGZOEVn-nxcKLsPD-z0Y)

Hello, yes I did. It ran as is but the direct edit on the data table does not persist.

**Comment by olvrcrls** [comment]
Just a follow-up on this one, I can update it now via the data table on a different database connection.
Also, I can update the column data I want to update via this kind of SELECT query:
```sql
SELECT id, column_to_update FROM table;
``` 

Weirdly enough, I cannot update the column value on my particular database and I cannot share it with you guys. For now, this is my way of using the software if I want to update some particular column from the data set.

I tried to use the software and update the column value via data table UI with a simpler database schema, it worked as expected. I guess the bug occurs for some index keys.

Ticket closed. Thank you, BoltSQL team 🙏🏼

**Comment by olvrcrls** [comment]
> Hi @olvrcrls, have you tried to run the updated query in the Preview dialog?
> 
> ![image](https://private-user-images.githubusercontent.com/4739616/285560018-69ffd20e-f8a3-41e4-a86c-023fb080d8b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwODE2MDUsIm5iZiI6MTcwMTA4MTMwNSwicGF0aCI6Ii80NzM5NjE2LzI4NTU2MDAxOC02OWZmZDIwZS1mOGEzLTQxZTQtYTg2Yy0wMjNmYjA4MGQ4YjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjdUMTAzNTA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2UwNmMzMDUxNDg4MDNmOTMxNDA5OWNiYTRlYTBlNmI0N2ZmY2UyMWY5Y2ZmZWFhMjM1NjU4NDU4NjlkN2U5NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.9UnFmSjb0yDadlUNTnO3uDAOcpGdvIKy2LJRz5Vj6HY)

I tried to run the preview on the database I encountered the bug with, the `WHERE` statement is not only referring to the `id` column it defers to a lot actually which is why it might be an index key problem.

Thank you though!

**Comment by huyphams** [comment]
Your table does not have primary, Bolt SQL uses primary for the where, if there is no primary, it will use all the columns.

But I think Bolt SQL should also check the unique not null index (same as primary).
